"""empty message

Revision ID: 1bae0abff421
Revises: 
Create Date: 2020-06-26 23:15:09.649193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bae0abff421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('special__codes',
    sa.Column('sc_id', sa.Integer(), nullable=False),
    sa.Column('code_type', sa.Enum('vendor_name', 'customer_name', 'GL_acct'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('sc_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.Enum('expense', 'revenue'), nullable=True),
    sa.Column('vendor_qb_id', sa.String(length=200), nullable=True),
    sa.Column('customer_qb_id', sa.String(length=200), nullable=True),
    sa.Column('GL_acct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('special__codes')
    op.drop_table('client')
    # ### end Alembic commands ###
