"""empty message

Revision ID: 38a71a401afa
Revises: 550cc03dacca
Create Date: 2020-07-22 23:24:04.158806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a71a401afa'
down_revision = '550cc03dacca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transaction_description')
    # ### end Alembic commands ###
