"""empty message

Revision ID: 550cc03dacca
Revises: 596c375d01e5
Create Date: 2020-07-02 18:03:08.868459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '550cc03dacca'
down_revision = '596c375d01e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='quick_books_credential')
    op.drop_table('quick_books_credential')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_books_credential',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('realmId', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'quick_books_credential', ['user_id'], unique=True)
    # ### end Alembic commands ###
