"""empty message

Revision ID: 596c375d01e5
Revises: 59fff3d45458
Create Date: 2020-07-02 17:27:29.512876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '596c375d01e5'
down_revision = '59fff3d45458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_books_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('realmId', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user', sa.Column('qb_code', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('qb_realmID', sa.String(length=255), nullable=True))
    op.drop_index('qb_id', table_name='user')
    op.create_unique_constraint(None, 'user', ['qb_code'])
    op.drop_column('user', 'qb_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('qb_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('qb_id', 'user', ['qb_id'], unique=True)
    op.drop_column('user', 'qb_realmID')
    op.drop_column('user', 'qb_code')
    op.drop_table('quick_books_credential')
    # ### end Alembic commands ###
