"""empty message

Revision ID: 59fff3d45458
Revises: 1bae0abff421
Create Date: 2020-07-02 16:15:50.063027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59fff3d45458'
down_revision = '1bae0abff421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['client_id'])
    op.create_unique_constraint(None, 'special__codes', ['sc_id'])
    op.add_column('transaction', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'transaction', ['transaction_id'])
    op.drop_constraint('transaction_ibfk_1', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'client', ['client_id'], ['client_id'])
    op.drop_column('transaction', 'client')
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('transaction', sa.Column('client', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_ibfk_1', 'transaction', 'client', ['client'], ['client_id'])
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_column('transaction', 'client_id')
    op.drop_constraint(None, 'special__codes', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    # ### end Alembic commands ###
