"""empty message

Revision ID: 725f621e8b44
Revises: 24bca81d2351
Create Date: 2020-09-04 16:52:05.008442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725f621e8b44'
down_revision = '24bca81d2351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('qb_token', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'qb_token')
    # ### end Alembic commands ###
